apiVersion: virtualservicecomponent.shibataka000.com/v1alpha1
kind: HTTPRouteBinding
metadata:
  name: httproutebinding-sample
spec:
  virtualServiceBaseRef:
    apiVersion: virtualservicecomponent.shibataka000.com/v1alpha1
    kind: VirtualServiceBase
    name: virtualservicebase-sample
    namespace: default
  httpRoute:
    match:
    - headers:
        key:
          exact: mysubset
    route:
    - destination:
        host: myhost
        subset: mysubset
